# Generated by Django 5.2.17 on 2026-08-20 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
    ]
