# Generated by Django 5.2.17 on 2026-08-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_fix_primary_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_dummy',
            field=models.BooleanField(default=False),
        ),
    ]
