# Generated by Django 6.0.6 on 2026-07-06 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('sub_category', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('price_npr', models.IntegerField()),
                ('ram_gb', models.IntegerField()),
                ('storage_gb', models.IntegerField()),
                ('processor', models.CharField(max_length=150)),
                ('gpu', models.CharField(max_length=150)),
                ('os', models.CharField(max_length=50)),
                ('battery_mah', models.IntegerField()),
                ('display_size_inches', models.FloatField()),
                ('display_type', models.CharField(max_length=50)),
                ('display_resolution', models.CharField(max_length=50)),
                ('refresh_rate_hz', models.IntegerField()),
                ('rear_camera_mp', models.IntegerField()),
                ('front_camera_mp', models.IntegerField()),
                ('fast_charging_watts', models.IntegerField()),
                ('weight_grams', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('warranty_years', models.IntegerField()),
                ('rating', models.FloatField()),
                ('num_ratings', models.IntegerField()),
                ('stock_quantity', models.IntegerField()),
                ('seller_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='placeholder.jpg', upload_to='product_images')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category')),
            ],
        ),
    ]
