# Generated by Django 5.2.17 on 2026-08-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productview_searchlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('khalti', 'Khalti'), ('cod', 'Cash on Delivery')], max_length=20, null=True),
        ),
    ]
