# Generated by Django 6.0.7 on 2026-08-20 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_cart_order_orderitem_cartitem'),
        ('catalog', '0005_productview_searchlog'),
    ]

    operations = [
    ]
