# Generated by Django 5.2.17 on 2026-08-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='seller_business_snapshot',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller_contact_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller_email_snapshot',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller_name_snapshot',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
